export const locations = [
    { name: "Delhi", href: "/digital-marketing-services-in-delhi" },
    // New Delhi
    { name: "New Delhi", href: "/digital-marketing-services-in-new-delhi" },

    // North Delhi
    { name: "Model Town", href: "/digital-marketing-services-in-model-town" },
    { name: "Civil Lines", href: "/digital-marketing-services-in-civil-lines" },
    { name: "Kamla Nagar", href: "/digital-marketing-services-in-kamla-nagar" },
    { name: "Shalimar Bagh", href: "/digital-marketing-services-in-shalimar-bagh" },
    { name: "Ashok Vihar", href: "/digital-marketing-services-in-ashok-vihar" },
    { name: "Pitampura", href: "/digital-marketing-services-in-pitampura" },
    { name: "Rohini", href: "/digital-marketing-services-in-rohini" },
    { name: "Prashant Vihar", href: "/digital-marketing-services-in-prashant-vihar" },
    { name: "Vijay Nagar", href: "/digital-marketing-services-in-vijay-nagar" },
    { name: "Mukherjee Nagar", href: "/digital-marketing-services-in-mukherjee-nagar" },
    { name: "GTB Nagar", href: "/digital-marketing-services-in-gtb-nagar" },
    { name: "Burari", href: "/digital-marketing-services-in-burari" },
    { name: "Alipur", href: "/digital-marketing-services-in-alipur" },
    { name: "Narela", href: "/digital-marketing-services-in-narela" },
    { name: "Bawana", href: "/digital-marketing-services-in-bawana" },

    // West Delhi
    { name: "Rajouri Garden", href: "/digital-marketing-services-in-rajouri-garden" },
    { name: "Punjabi Bagh", href: "/digital-marketing-services-in-punjabi-bagh" },
    { name: "Janakpuri", href: "/digital-marketing-services-in-janakpuri" },
    { name: "Tilak Nagar", href: "/digital-marketing-services-in-tilak-nagar" },
    { name: "Uttam Nagar", href: "/digital-marketing-services-in-uttam-nagar" },
    { name: "Vikaspuri", href: "/digital-marketing-services-in-vikaspuri" },
    { name: "Paschim Vihar", href: "/digital-marketing-services-in-paschim-vihar" },
    { name: "Subhash Nagar", href: "/digital-marketing-services-in-subhash-nagar" },
    { name: "Hari Nagar", href: "/digital-marketing-services-in-hari-nagar" },
    { name: "Dwarka", href: "/digital-marketing-services-in-dwarka" },
    { name: "Dabri", href: "/digital-marketing-services-in-dabri" },
    { name: "Najafgarh", href: "/digital-marketing-services-in-najafgarh" },

    // Central Delhi
    { name: "Connaught Place", href: "/digital-marketing-services-in-connaught-place" },
    { name: "Karol Bagh", href: "/digital-marketing-services-in-karol-bagh" },
    { name: "Paharganj", href: "/digital-marketing-services-in-paharganj" },
    { name: "Patel Nagar", href: "/digital-marketing-services-in-patel-nagar" },
    { name: "Rajendra Place", href: "/digital-marketing-services-in-rajendra-place" },
    { name: "Jhandewalan", href: "/digital-marketing-services-in-jhandewalan" },
    { name: "Daryaganj", href: "/digital-marketing-services-in-daryaganj" },
    { name: "Chandni Chowk", href: "/digital-marketing-services-in-chandni-chowk" },
    { name: "ITO", href: "/digital-marketing-services-in-ito" },
    { name: "Barakhamba Road", href: "/digital-marketing-services-in-barakhamba-road" },

    // South Delhi
    { name: "Saket", href: "/digital-marketing-services-in-saket" },
    { name: "Malviya Nagar", href: "/digital-marketing-services-in-malviya-nagar" },
    { name: "Hauz Khas", href: "/digital-marketing-services-in-hauz-khas" },
    { name: "Green Park", href: "/digital-marketing-services-in-green-park" },
    { name: "Greater Kailash", href: "/digital-marketing-services-in-greater-kailash" },
    { name: "Defence Colony", href: "/digital-marketing-services-in-defence-colony" },
    { name: "Lajpat Nagar", href: "/digital-marketing-services-in-lajpat-nagar" },
    { name: "South Extension", href: "/digital-marketing-services-in-south-extension" },
    { name: "Vasant Kunj", href: "/digital-marketing-services-in-vasant-kunj" },
    { name: "Mehrauli", href: "/digital-marketing-services-in-mehrauli" },
    { name: "Chhatarpur", href: "/digital-marketing-services-in-chhatarpur" },
    { name: "Kalkaji", href: "/digital-marketing-services-in-kalkaji" },
    { name: "CR Park", href: "/digital-marketing-services-in-cr-park" },
    { name: "Nehru Place", href: "/digital-marketing-services-in-nehru-place" },

    // East Delhi
    { name: "Laxmi Nagar", href: "/digital-marketing-services-in-laxmi-nagar" },
    { name: "Preet Vihar", href: "/digital-marketing-services-in-preet-vihar" },
    { name: "Patparganj", href: "/digital-marketing-services-in-patparganj" },
    { name: "Anand Vihar", href: "/digital-marketing-services-in-anand-vihar" },
    { name: "Shahdara", href: "/digital-marketing-services-in-shahdara" },
    { name: "Vivek Vihar", href: "/digital-marketing-services-in-vivek-vihar" },
    { name: "Mayur Vihar", href: "/digital-marketing-services-in-mayur-vihar" },
    { name: "IP Extension", href: "/digital-marketing-services-in-ip-extension" },
    { name: "Krishna Nagar", href: "/digital-marketing-services-in-krishna-nagar" },
    { name: "Karkardooma", href: "/digital-marketing-services-in-karkardooma" },
    { name: "Geeta Colony", href: "/digital-marketing-services-in-geeta-colony" },
    { name: "Gandhi Nagar", href: "/digital-marketing-services-in-gandhi-nagar" },
];